version: '3.9'

services:
  postgres:
    container_name: electricity_timescale
    image: timescale/timescaledb:latest-pg12
    restart: always
    command: ['-c', 'shared_buffers=256MB', '-c', 'max_connections=200']
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"
    volumes:
      - electricity-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    # networks:
    #   - electricity-net

  fetch:
    container_name: electricity_fetch
    build: .
    restart: always
    environment:
      - "DB_HOSTNAME=${DB_HOSTNAME}"
      - "DB_PORT=${DB_PORT}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    links:
      - "postgres:${DB_HOSTNAME}"
    # networks:
    #   - electricity-net

networks:
  electricity-net:

volumes:
  electricity-db:
